server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend:3001;
    client_max_body_size 25m;
  }

  location / {
    try_files $uri /index.html;
  }
}
